### PR TITLE
RHODA 0.2.0 verbiage updates

### PR DESCRIPTION
**Pull request by jeremyary**
Hi all, attempting our team's first commit so I'm also figuring out the process. PTAL, thanks!

### CODE REVIEW

**Comment by jeremyary** [comment]
@aneelac22 @Hyperkid123 looking at previous work in this repo, seems that I need to first open this PR to master, and then once approved, open PR's to target the `master-stable` `prod-stable` and `prod-beta` branches? Thanks for TAL!

**Review by aneelac22 — COMMENTED** [review]
Looks good! Can you run lint? The build is failing

**Review by aneelac22 — APPROVED** [review]

**Comment by jeremyary** [comment]
Thanks @aneelac22! Assuming I'm good to merge up & create the other three PR's now. Do the merges on the various branches here act as gatekeeping for the various enviros? Just want to make sure I'm playing by the rules, but I'm not up to speed for usual insights processes. Really appreciate your time and assitance!

**Comment by aneelac22** [comment]
@jeremyary yes, that's basically it, I can merge this and based on the timeline you can create other PR's for other environments and if you have more changes that go in prod you should try to do all at the same time

**Comment by jeremyary** [comment]
Great, thank you! Nothing more for this release, a nice and easy first commit to ease into and figure out pipelines/processes :)

**Pull request merged**
