### PR TITLE
DBAAS-1068: Add install it on cluster button to dashboard

### PR DESCRIPTION
**Pull request by yzhao583**
Jira: [https://issues.redhat.com/browse/DBAAS-1068](https://issues.redhat.com/browse/DBAAS-1068)

- Added the "Install it on a cluster" flow.
- Modified the description text.
- Added the "Try it in the developer sandbox" flow.

image
image
image

### CODE REVIEW

**Review by jeremyary — APPROVED** [review]

**Comment by jeremyary** [comment]
Reminder we'll have 4 total PR's for the different enviros, but this one should allow us to test in staging-beta

**Comment by jeremyary** [comment]
Looks like we've got some Lint issues to work through: https://app.travis-ci.com/github/RedHatInsights/dbaas-ui/jobs/593760090

**Comment by jeremyary** [comment]
@yzhao583 TAL and see what you think of the failed lint job? Looks like it may just be local tab formatting, but worth looking in to

**Comment by yzhao583** [comment]
@jeremyary Thanks for the review! Yes, we got some lint issues, and I fixed them. Now everything looks good to me, is there anything else I missed?

**Review by jeremyary — APPROVED** [review]

**Comment by jeremyary** [comment]
Thanks @yzhao583! This content should be available at staging-beta console shortly after merging, so we'll use that for QE validation and once tested and approved, we can merge up the other matching PR's.

**Pull request merged**
